SuperheroCreator/Controllers/HeroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SuperheroCreator.Models;

namespace SuperheroCreator.Controllers
{
    public class HeroController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();

        public ActionResult Index()
        {
            // string currentUserId = User.Identity.GetUserId();
            ViewBag.BackgroundImage = "https://images3.alphacoders.com/212/212607.jpg";
            return View(context.Heroes);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(int ID)  
        {
            var hero = context.Heroes.Where(h => h.ID == ID).FirstOrDefault();
            return View(hero);
        }

        public ActionResult Edit(int ID) 
        {
            var hero = context.Heroes.Where(h => h.ID == ID).FirstOrDefault();
            return View(hero);
        }

        public ActionResult Details(int ID)
        {
            var hero = context.Heroes.Where(h => h.ID == ID).FirstOrDefault();
            return View(hero);
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "Name,AlterEgo,PrimaryAbility,SecondaryAbility,Catchphrase")]Heroes Hero)
        {
            context.Heroes.Add(Hero);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit([Bind(Include = "ID,Name,AlterEgo,PrimaryAbility,SecondaryAbility,Catchphrase")]Heroes Hero)
        {
            var OGHero= context.Heroes.Where(h => h.ID == Hero.ID).FirstOrDefault();
            OGHero.Name = Hero.Name;
            OGHero.AlterEgo = Hero.AlterEgo;
            OGHero.PrimaryAbility = Hero.PrimaryAbility;
            OGHero.SecondaryAbility = Hero.SecondaryAbility;
            OGHero.CatchPhrase = Hero.CatchPhrase;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost,ActionName("Delete")]
        public ActionResult DeleteDBSide(int ID)
        {
            var hero = context.Heroes.Find(ID);
            context.Heroes.Remove(hero);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SuperheroCreator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">     
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @Html.ActionLink("Hero Creator Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })        
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav" mr-auto>
                    <li class=" nav-item">@Html.ActionLink("About Me", "About", "Home")</li>
                    <li class=" nav-item">@Html.ActionLink("Contact Me", "Contact", "Home")</li>
                    <li class=" nav-item">@Html.ActionLink("Heroes DB Home", "Index", "Hero")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
       </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           @* <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>